# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(387, 204)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.lbl_num1 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_num1.setGeometry(QtCore.QRect(70, 50, 47, 13))
        self.lbl_num1.setObjectName("lbl_num1")
        
        self.lbl_num2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_num2.setGeometry(QtCore.QRect(70, 90, 47, 13))
        self.lbl_num2.setObjectName("lbl_num2")
        
        self.txt_num1 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_num1.setGeometry(QtCore.QRect(100, 50, 113, 20))
        self.txt_num1.setObjectName("txt_num1")
        
        self.txt_num2 = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_num2.setGeometry(QtCore.QRect(100, 90, 113, 20))
        self.txt_num2.setObjectName("txt_num2")
        
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setGeometry(QtCore.QRect(100, 130, 21, 23))
        self.btn_add.setObjectName("btn_add")
        
        self.btn_extract = QtWidgets.QPushButton(self.centralwidget)
        self.btn_extract.setGeometry(QtCore.QRect(130, 130, 21, 23))
        self.btn_extract.setObjectName("btn_extract")
        
        self.btn_divide = QtWidgets.QPushButton(self.centralwidget)
        self.btn_divide.setGeometry(QtCore.QRect(160, 130, 21, 23))
        self.btn_divide.setObjectName("btn_divide")
        
        self.btn_multiply = QtWidgets.QPushButton(self.centralwidget)
        self.btn_multiply.setGeometry(QtCore.QRect(190, 130, 21, 23))
        self.btn_multiply.setObjectName("btn_multiply")
        
        self.lbl_result = QtWidgets.QLabel(self.centralwidget)
        self.lbl_result.setGeometry(QtCore.QRect(260, 70, 47, 13))
        self.lbl_result.setToolTip("")
        self.lbl_result.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_result.setObjectName("lbl_result")
        
        self.lbl_result2 = QtWidgets.QLabel(self.centralwidget)
        self.lbl_result2.setGeometry(QtCore.QRect(260, 90, 47, 13))
        self.lbl_result2.setToolTip("")
        self.lbl_result2.setText("")
        self.lbl_result2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_result2.setObjectName("lbl_result2")
        
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 387, 21))
        self.menubar.setObjectName("menubar")
        
        MainWindow.setMenuBar(self.menubar)
        
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        
        self.lbl_num1.setText(_translate("MainWindow", "Num"))
        self.lbl_num2.setText(_translate("MainWindow", "Num"))
        self.btn_add.setText(_translate("MainWindow", "+"))
        self.btn_extract.setText(_translate("MainWindow", "-"))
        self.btn_divide.setText(_translate("MainWindow", "/"))
        self.btn_multiply.setText(_translate("MainWindow", "*"))
        self.lbl_result.setText(_translate("MainWindow", "RESULT"))


class App(QtWidgets.QMainWindow):
    def __init__(self):
        super(App, self).__init__()
        self.ui = MainWindow()
        self.ui.setupUi(self)
        self.ui.btn_add.clicked.connect(self.calc)
        self.ui.btn_divide.clicked.connect(self.calc)
        self.ui.btn_extract.clicked.connect(self.calc)
        self.ui.btn_multiply.clicked.connect(self.calc)

    def calc(self):
        sender = self.sender().text()
        
        try:
            if(sender == "+"):
                result = int(self.ui.txt_num1.text()) + int(self.ui.txt_num2.text())
            elif(sender == "-"):
                result = int(self.ui.txt_num1.text()) - int(self.ui.txt_num2.text())
            elif(sender == "/"):
                result = int(self.ui.txt_num1.text()) / int(self.ui.txt_num2.text())
            elif(sender == "*"):
                result = int(self.ui.txt_num1.text()) * int(self.ui.txt_num2.text())
        except:
            result = 0

        self.ui.lbl_result2.setText(str(result))
    
def app():
    app = QtWidgets.QApplication(sys.argv)
    win = App()
    win.show()
    sys.exit(app.exec_())

app()


